package org.octopus.enums;

public enum LexicalState {
    INITIAL,
    NUMBER,
    FRACTION,
    VAR,
    STRING,
    VERIFY_COMMENT,
    BLOCK_COMMENT,
    END_BLOCK_COMMENT,
    REGULAR_COMMENT,
    HAS_EQUALS_IN_LOWER_THAN,
    HAS_EQUALS_IN_HIGHER_THAN,
    HAS_EQUALS_IN_ADD,
    HAS_EQUALS_IN_SUBTRACT,
    HAS_EQUALS_IN_EQUALS,
    HAS_EQUALS_IN_DIFFERENT,
    HAS_EQUALS_IN_MULTIPLY,
    HAS_EQUALS_IN_DIVIDE,
    LOGIC_OR,
    LOGIC_AND

}
